name: "Setup Butler"
description: "Downloads Itch.io's CI/CD tool, Butler, as an artifact"
author: "vega-star"

inputs:
  BUTLER-ARTIFACT:
    description: 'Butler zip file uploaded as artifact previously'
    required: true

runs:
  using: "composite"
  steps:
    - name: Download butler
      uses: actions/download-artifact@v4
      with:
        name: BUTLER-ARTIFACT

    - name: Uncompact butler
      shell: bash
      run: unzip butler.zip && chmod +x butler

    - name: Butler check
      shell: bash
      run: ./butler -V