name: 'Deploy executables only'

on: workflow_dispatch

env:
  GAME_ID: lightkeepers

jobs:
    upload:
        name: 'Butler validation'
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        steps: 
            # Checkout repo to Github Actions runner
            - name: Checkout
              uses: actions/checkout@v4.1.1
              with:
                lfs: true
            
            # Checkout LFS objects 
            # These objects are game executables stored in other places because GitHub has a file size limit
            - name: Checkout LFS objects
              run: git lfs checkout
            
            # Butler fresh install
            - name: Butler fresh install
              run:
                curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
                unzip butler.zip
                chmod +x butler
            
            # Butler check
            - name: Butler check
              run: ./butler -V

            # Authenticate in butler with secret
            - id: 'auth'
              name: 'Itch.io login with Butler'
              env:
                BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
              run: ./butler login
    
            # Upload Linux executable
            - name: Upload (Linux)
              env:
                BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
              run:
                ./butler push exports/linux nyeptun/${{ env.GAME_ID }}:linux --userversion ${{ github.event.inputs.version }}
    
            # Upload Windows executable
            - name: Upload (Windows)
              env:
                BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
              run:
                ./butler push exports/windows nyeptun/${{ env.GAME_ID }}:win64 --userversion ${{ github.event.inputs.version }}